#spring.application.name=spring

spring:
  datasource:
    #url: jdbc:mysql://tempdb.c7kwsyswc6i7.ap-northeast-2.rds.amazonaws.com:3306/study
    url: ${AWS_DB_URL}
    #username: root
    username: ${AWS_DB_USER}
    #password: EarthUsPlogUs20240405!
    password: ${AWS_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
          # if you're not creating DB first time,
          # make sure to make auto: update
          # auto: update modifies on only changed things
#          auto: create
          # JPA creates tables on Database by searching @Entity
          # forms new tables after deleting existing tables
          # if you're creating DB first time,
          # DataGrip will alert error
          # cause there's noting to delete existing tables
          # so it's OK
        default_batch_fetch_size: 1000

cloud:
  aws:
    s3:
      bucket: umc-5th-practice
      path:
        review: review
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      # Environment variables
      #accessKey: Springboot accessKey
      accessKey: ${AWS_ACCESS_KEY_ID}
      #secretKey: Springboot secretKey
      secretKey: ${AWS_SECRET_ACCESS_KEY}